jobs:
  include:
  - os: linux
    dist: bionic
    arch: arm64
language: cpp
cache:
  directories:
  - "$HOME/Downloads/source"
  - "$HOME/Documents/temp/build/AmiKo-wx/curl"
  - "$HOME/Documents/temp/build/AmiKo-wx/json"
  - "$HOME/Documents/temp/build/AmiKo-wx/wxWidgets-3.1.4-mk"
  - "$HOME/Applications/AmiKo-wx/curl"
  - "$HOME/Applications/AmiKo-wx/json"
  - "$HOME/Applications/AmiKo-wx/wxWidgets-3.1.4"
env:
  global:
  - secure: cmmB8wEUhlMozbkGE13xpR/aIoQ8pSE7/DAcF74eeNjkQW7nQzyx48s8vc8w4bO2dsBE/J9qYuKZtU/47ZtmmDhRkwqmVhgOSf6q1N7XUW7usrioxMe1BC5KrKDwv3l/euocDzDOQri5xN3KK+ZOpdUuRjT5lzggGLp+lJwVL1DdlntTdQ4S250C5Dp2ON0xr1PUF4GSylZHvmPpVdFJAJ1HNrOpl01baEhZ/3RunSdhcdXUdjo+JYAo47zA044xFIJFZgEmCc8RQ6UCevADjRd+9junC+Fd+g50w4iengVCYZC2LYq8kIpviUXB61xxF9La90fE8iuyeffypuMGy+YYhTJ2OL9PYoghleXfRUvu6kfBx3SM3lepmr7UlKsa6KOSHszmCVhWN6dmLQcwmOG42fEeLZ3LIB0S9DnLbu7O7ZTkCUMGMF4xUcMC4mAfcWxpumMBj8uaxymDDBdUNWOvTBTrFP/BUk6mikkkmclxwo81iI326P0oYguLtZ6hvyxyMVL3IFhpwNlTfQMpeKUcertayDyOWLNio8gTbGh99sWjj1ADIsnH8gYFla84lFCeNHpWFeInmuXD/eRmYygLy1BqMYvuUnQAEF1hVuBPk8fr00MJfw0KTiepRvSCRjYsmoSsA02kHmbD0vujbeBsXW64rmkL4+0sfXGJWks=
  - secure: FDNfZBRlf+ydXRtOIKaFaoaKqkBcXr9YCf8Lt+wvTUhvJqnIhqfuF3Xcx5x3Z4hDzeUzqm70qVOhGDu/Fvx2oGznNX0MpI4sXmGSvDRuEIrcb0PQ3Uz2TegifX2bs2CspW3dpbZIaDwqoAQBcVdjrLyqjUSp06FwqV6c2yCYloTgyWsp8ydDVCW/K2rQc9vVubZBzQjNEHskHwhO+TFss18RxHbuQiDKcXISVH3JBypZP+7LDofLVhAumjjtI83djxXBO6tVxNFjhiwS3CC0Q5urTQjQii4XX8hXuokUFOq57A7hc9/eS20aqxPRVzxMopvCbwAnHDs6igxiRsNRtpEdfHK618XEG7FmFWXZ8Mfxah7rUIaQlPP6J1m8MnRblCGNwOBarbzIEEJTBWH7l7bIU1shUH9AgpcG9nEwagvSKxFLd5mcppLFBVyiy+rQVMlIaJzdUswSF5JuEHuZuSwQQUl1Ea0Vs8p7K5BlEE9YQAhkqv6QecRKfQAeBBvJKIKmzpF+4K4O+BRYZp6Q+pZ6nC8uHiK+fd3jaFneHj/Rf+igyVru88ofsgn2zbFRrfbwwrAFP+Fx24d486mSRXeBLzjSDDiQKlHLDg96TCrsQO1vWs/pu/wswXytmpiebX8JUJDnr1qtdAWqFGcKgEGeMyMX9mRor6fwpFQB3Ao=
  - secure: 0klyO+K8H1NAkOpbMk0DATc2O65ENqdpHHzSHpI1SyIPcwrKDQc3OmQOzwn+8WqwHKA8gcjzdjagrc8o1eBwuiAfV6MUEOOkvVBCGrp+t/Lrb38jeahqtbQ2s4vGbneW/ZSrGYDl4vo1I8WcQw383T0hSuZ7DamWl8kgrKeA1nevPktqbjr025WLi2QN86n/uCo4Pot0pURzlHbD1nfH5o6FbG8JhXxrkYCdUck1k8EdCWRHbfBkXzMlBjCM1znmq1pFx4+2yUz9wIdl8R193nSXqfcippGx9s0Y7ZrAP/BDUx6WvIkdKgmD+lGfE7AEXLmxwZCwczLZZ1xLVFK52ylxe1nglhzBntwBQkc7V1wW80oU5rvWCh0DpzvQUvcgphYoO0uRykZGEdGiFAbvs8mih4Rk2NnlPfcwsAem41eb0OAv/eOPUBa4CvxnB30q5XMfI/v+z/GcViPf+byz++BRqgRwzPg6V7eVdQDimTJTygdap1OPVMqJFGKdYqw7Um6d4NexWKudBblSuU0HMs2c54CuFopaFd5zX1vF142qvYdSHoxYyewUGSMhuBF9WrvZ9gurUg/7tXHDXZTw8PV5JYeiwDLxYPtGJsGcZWicMma6UbLArpIUma5YXYtBWXoxnyCFlG+XAut7sXC5xUgWhvCb687F3WTbr4dOfdA=
  - secure: HT9gv3lgL72BFdvCDsp9V5qNLX0QawvbyGxMeoxmBGHMNNh0CTmhJ3WE5km89TKrvsQlnvCsmg6AT+O8iqpyrH5L4nIdKmhEmhuhdO8qvcvMJ+nKArcfoj0/p+337MAwGswn4FPi+djf6PNc6NAA82shIQXkg/hVa3y+HF9N/y8rS3N7UkGNYsNa54y7YjWiXn4xYOzhEAiadMIVYKGX+rh91Fie+VKF2ePf3gn4akCqN/jtAyi9i03cNASVocUhbHqER1rQ5GPqVzq5ebuABagPbl8CG/R/KElymA36YLRZP4KzzVHWc2P81eJmpZROpp9F12yD24x2DQiUiZ5JnZ+Nqc9BGUSX7rndG1qOtrK+89fDPnCp5/zxdTyUznuo9JLic9SXgaYf18niEilsvY4cgEuaOriejGYHuF37FUpF9jiQ3AsOdfk7Nxe1nNhNKztaSYV7s/FinSPMZOgSuOZGu9KS1pmDVFbFm6LfqCeA9hsewF4dL5NEjvduwZB1izv4+kGwMNVr0Rbt2rdvdaL1Evh31EQJ76C+v5CSrxOuBTtmbgfo3n+Cc/xUDV4vuVjViPXMlbZniN4oQ9mMbYxMiswNgiLDEqYYX4/dBjLP/pYI/OMr3G0A4UitvoUbQkY/APzFpIIL9QQJP7lSj1VSWcpvBof5yR/gMTZvvwU=
install: |
  sudo apt update
  sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev libssl-dev pcscd libpcsclite-dev rpm
  cp seed.in.conf seed.conf
  sed -e "s/#STEP/STEP/g" steps.in.conf > steps.conf

  sed -i.bak -e "s/AMIKO_GOOGLE_CLIENT_ID=''/AMIKO_GOOGLE_CLIENT_ID='$AMIKO_GOOGLE_CLIENT_ID'/g" seed.conf
  sed -i.bak -e "s/AMIKO_GOOGLE_CLIENT_SECRET=''/AMIKO_GOOGLE_CLIENT_SECRET='$AMIKO_GOOGLE_CLIENT_SECRET'/g" seed.conf
  sed -i.bak -e "s/COMED_GOOGLE_CLIENT_ID=''/COMED_GOOGLE_CLIENT_ID='$COMED_GOOGLE_CLIENT_ID'/g" seed.conf
  sed -i.bak -e "s/COMED_GOOGLE_CLIENT_SECRET=''/COMED_GOOGLE_CLIENT_SECRET='$COMED_GOOGLE_CLIENT_SECRET'/g" seed.conf
script: |
  sudo ./build.sh
  CURRENT_VERSION=$(./check_need_release.sh)
  if [ -z $CURRENT_VERSION ] ; then
    echo "No need to create release"
  else
    echo "Need to create release"
    echo "Creating release"
    # Set up git user name and tag this commit
    git config --local user.name "Travis"
    git config --local user.email "travis@b123400.net"
    export TRAVIS_TAG=$CURRENT_VERSION
    git tag $CURRENT_VERSION
    pushd ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/
    for filename in *.rpm; do sudo mv $filename ${filename%.*}-arm64.rpm; done;
    for filename in *.tar.gz; do sudo mv $filename ${filename%.tar.gz}-arm64.tar.gz; done;
    for filename in *.deb; do sudo mv $filename ${filename%.*}-arm64.deb; done;
    popd
  fi
deploy:
  provider: releases
  api_key:
    secure: lf6r6ACfLejyHeHXEfdCb/136HeLQoar+b3rPBk8EiNR3gqsJ4dv6Z2kPsx8z9vPoT6RHeY/8eIZfafrjCXFipY3C1bZrJ9FvYy2xxOchHxwrBTZr4EkOXHH4UW39T4u/hZjZi6oJ/fPydQV56QhNVz753VIdGisWqD8abSucL94lm2QG9fkiBDLo7ZNG0VZeLUN4iCfm/8zOpuC/59rwT2pR82lAbqR75q3colsh9XFUPrZLS68+8mqH3BkmkD6WsXCGgXinTDM04PUhoWSUcJJqgtGhSKzM0j3wO6sTDmWo+16WFG+HmWZqhlmGO7reK4ylLLrp0JEl9PSpp02bzgADHnAoxc+RDVFBwPPEYzuVhIdtP47BLnWi9TC2SNNvEF6g/3Occ7cgAIsXnx7UFwDIcU2/0+8Kj2RJTqUu3478rvHTEsRB7YjkMPDMTqySo85LCKQYdTuIRgMTx3TwWfuHkk54TFOQbyBKb+eKWRr3LguVzWCy4WnM+fvYLqt1O81Tz92JRhG7uUld8Tq6jVEbiAohGeFog30Mn5Kfr1RkW3pQYVgtwG/2OVG0F6PkTfmbPF2/ZFCAHJA4oY+adI4Uby1GBuG4ZyZRayA8DwVtHViz9JPyLBkErxhTxNSu5ofCfAFc6aVICWZC8UZ+YLVUxMUE8XAJwRkP74yl1I=
  file_glob: true
  file:
  - "/home/travis/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.rpm"
  - "/home/travis/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.tar.gz"
  - "/home/travis/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.deb"
  skip_cleanup: true
  on:
    branch: master
    condition: "-n $CURRENT_VERSION"
