#ifndef __AboutDialog__
#define __AboutDialog__

/**
@file
Subclass of AboutDialogBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

/** Implementing AboutDialogBase */
class AboutDialog : public AboutDialogBase
{
	public:
		/** Constructor */
		AboutDialog( wxWindow* parent );
	//// end generated class members

	private:
		void OnCloseClick( wxCommandEvent& event );
		void OnUpdateClick( wxCommandEvent& event );
		void CheckForUpdate();
};

#endif // __AboutDialog__
