#ifndef __GoogleAuthSheet__
#define __GoogleAuthSheet__

/**
@file
Subclass of GoogleAuthSheet, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

/** Implementing GoogleAuthSheet */
class GoogleAuthSheet : public GoogleAuthSheetBase
{
	public:
		/** Constructor */
		GoogleAuthSheet( wxWindow* parent );
	//// end generated class members

		void LoadAuthURL();

	protected:
		void OnCloseClicked( wxCommandEvent& event );
		void OnWebViewTitleChanged( wxWebViewEvent& event );

	private:
		DECLARE_EVENT_TABLE()
};

#endif // __GoogleAuthSheet__
