#ifndef __GoogleAuthCopySheet__
#define __GoogleAuthCopySheet__

/**
@file
Subclass of GoogleAuthCopySheetBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

/** Implementing GoogleAuthCopySheetBase */
class GoogleAuthCopySheet : public GoogleAuthCopySheetBase
{
	protected:
		// Handlers for GoogleAuthCopySheetBase events.
		void OnClickedOpenInBrowser( wxCommandEvent& event );
		void OnCodeChanged( wxCommandEvent& event );
		void OnClickedCancel( wxCommandEvent& event );
		void OnClickedOK( wxCommandEvent& event );
	public:
		/** Constructor */
		GoogleAuthCopySheet( wxWindow* parent );
	//// end generated class members


};

#endif // __GoogleAuthCopySheet__
