#ifndef __MainWindow__
#define __MainWindow__

/**
@file
Subclass of MainWindowBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

/** Implementing MainWindowBase */
class MainWindow : public MainWindowBase
{
	public:
		/** Constructor */
		MainWindow( wxWindow* parent );
	//// end generated class members


};

#endif // __MainWindow__
