#ifndef __OperatorIDSheet__
#define __OperatorIDSheet__

/**
@file
Subclass of OperatorIDSheetBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

/** Implementing OperatorIDSheetBase */
class OperatorIDSheet : public OperatorIDSheetBase
{
	public:
		/** Constructor */
		OperatorIDSheet( wxWindow* parent );
	//// end generated class members



};

#endif // __OperatorIDSheet__
