#ifndef __PatientSheet__
#define __PatientSheet__

/**
@file
Subclass of PatientSheetBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

#include <vector>

class Patient;
class PatientDBAdapter;

/** Implementing PatientSheetBase */
class PatientSheet : public PatientSheetBase
{
	protected:
		// Handlers for PatientSheetBase events.
		void OnSavePatient( wxCommandEvent& event );
	public:
		/** Constructor */
		PatientSheet( wxWindow* parent );
	//// end generated class members

    Patient *retrievePatient();
    Patient * getAllFields();
    bool validateFields(Patient *patient);
    
    // 30
    PatientDBAdapter *mPatientDb;

private:
    // .m 35
    Patient *mSelectedPatient;
    // .m 37
    std::vector<Patient *> mArrayOfPatients;
    std::vector<Patient *> mFilteredArrayOfPatients;
    wxString mPatientUUID;
    bool mABContactsVisible;    // These are the contacts in the address book
    bool mSearchFiltered;
    bool mFemale;
};

#endif // __PatientSheet__
