#ifndef __PatientSheet__
#define __PatientSheet__

/**
@file
Subclass of PatientSheetBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

class Patient;

/** Implementing PatientSheetBase */
class PatientSheet : public PatientSheetBase
{
	public:
		/** Constructor */
		PatientSheet( wxWindow* parent );
	//// end generated class members

        Patient *retrievePatient();
        
    private:
        // .m 35
        Patient *mSelectedPatient;

};

#endif // __PatientSheet__
