#ifndef __SplashWindow__
#define __SplashWindow__

/**
@file
Subclass of SplashWindowBase, which is generated by wxFormBuilder.
*/

#include "MainWindowBase.h"

//// end generated include

/** Implementing SplashWindowBase */
class SplashWindow : public SplashWindowBase
{
	public:
		/** Constructor */
		SplashWindow( wxWindow* parent );
	//// end generated class members

};

#endif // __SplashWindow__
